### ISSUE TITLE
submit pre-test 

### ISSUE THREAD

**Issue by 0xairdropfarmer** [thelivingos/livingos-mobile-challenge-2019#1]
not done yet but the main feature still did
 https://github.com/krissnawat/livingos-mobile-challenge-2019

Best 
Kris

**Comment by SiwakornSitti** [comment]
Thank for submitting your test but I have 2 questions.
before I make any decision

1.) How long you're spending with this test?
2.) How long you would need to make it completely?

**Comment by 0xairdropfarmer** [comment]
1. two days
2. may be more three days

**Comment by SiwakornSitti** [comment]
@krissnawat 	
I reviewed your test already. I could say. It's not passed. 
When I create this test. Actually, I expected a candidate should be done an assignment within 3 days. But if you have a good reason. you can explain why you need more than 3 days to do assignment. I can give you more 2 days to get this assignment done.

**Comment by SiwakornSitti** [comment]
@krissnawat Do you still want to send an assignment?
So, if we didn't receive any response. We'll close the issue by tomorrow.

**Comment by SiwakornSitti** [comment]
It's closed because we got no reply from candidate.
